'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const crypto=require('node:crypto');
const C=require('../src/core.js');
const R=require('../src/report.js');
const cfg={nominal_v:3.3,trip_v:3,recover_v:3.1};
const map={time_column:'t',voltage_column:'v',time_unit:'s',voltage_unit:'V'};
const rows=v=>v.map((v,i)=>({t:i,v}));
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-10,`${a} != ${b}`);
test('triangular event has analytical crossing times',()=>{const r=C.analyze(rows([3.3,3.3,2.7,2.7,3.3]),cfg);assert.equal(r.events.length,1);close(r.events[0].start_s,1.5);close(r.events[0].end_s,3+2/3);close(r.events[0].duration_s,13/6);close(r.capture.minimum_v,2.7);assert.equal(r.events[0].complete,true);});
test('hysteresis keeps one event through threshold chatter',()=>{const r=C.analyze(rows([3.3,2.9,3.01,2.99,3.09,3.3]),{...cfg,recover_v:3.08});assert.equal(r.events.length,1);});
test('strict trip threshold does not count mere equality',()=>{assert.equal(C.analyze(rows([3.3,3,3.3]),cfg).events.length,0);});
test('entry at a previous sample exactly equal to trip',()=>{close(C.analyze(rows([3,2.8,3.3]),cfg).events[0].start_s,0);});
test('capture-start event is left-censored',()=>{const e=C.analyze(rows([2.8,2.9,3.3]),cfg).events[0];assert.equal(e.left_censored,true);assert.equal(e.complete,false);assert.equal(e.start_bracket_s,null);});
test('capture-end event is right-censored',()=>{const e=C.analyze(rows([3.3,2.8,2.7]),cfg).events[0];assert.equal(e.right_censored,true);assert.equal(e.end_reason,'capture_end');});
test('all-low capture has two censored ends',()=>{const e=C.analyze(rows([2.8,2.8,2.8]),cfg).events[0];assert.ok(e.left_censored&&e.right_censored);close(e.duration_s,2);});
test('minimum duration filters complete events but preserves raw minimum',()=>{const r=C.analyze(rows([3.3,2.9,3.3]),{...cfg,min_duration_s:1});assert.equal(r.events.length,0);assert.equal(r.excluded_events.length,1);close(r.capture.minimum_v,2.9);});
test('incomplete short events are not silently duration-filtered',()=>{const r=C.analyze(rows([3.3,2.9]),{...cfg,min_duration_s:5});assert.equal(r.events.length,1);assert.equal(r.events[0].complete,false);});
test('gap splits a low event and blocks interpolation',()=>{const s=[{t:0,v:3.3},{t:1,v:2.8},{t:2,v:2.7},{t:10,v:2.7},{t:11,v:3.3}];const r=C.analyze(s,cfg);assert.equal(r.gaps.length,1);assert.equal(r.events.length,2);assert.equal(r.events[0].right_censored,true);assert.equal(r.events[1].left_censored,true);close(r.events[0].end_s,2);close(r.events[1].start_s,10);close(r.capture.observed_span_s,3);});
test('rising trigger is associated only within configured window',()=>{const s=rows([3.3,3.3,2.7,3.3]).map((s,i)=>({...s,trigger:i>=1?3.3:0}));const r=C.analyze(s,{...cfg,trigger_window_s:2});close(r.triggers[0].time_s,.5);close(r.events[0].trigger_lag_s,1);assert.equal(C.analyze(s,{...cfg,trigger_window_s:.1}).events[0].trigger_lag_s,null);});
test('falling trigger selection',()=>{const s=rows([3.3,3.3,2.7,3.3]).map((s,i)=>({...s,trigger:i===0?3.3:0}));close(C.analyze(s,{...cfg,trigger_edge:'falling',trigger_window_s:2}).events[0].trigger_lag_s,1);});
test('future trigger is never associated with an earlier onset',()=>{const s=rows([3.3,2.7,2.7,3.3]).map((s,i)=>({...s,trigger:i>=2?3.3:0}));assert.equal(C.analyze(s,{...cfg,trigger_window_s:10}).events[0].trigger_lag_s,null);});
test('trigger association cannot cross a sampling gap',()=>{const s=[{t:0,v:3.3,trigger:0},{t:1,v:3.3,trigger:3.3},{t:2,v:3.3,trigger:3.3},{t:10,v:3.3,trigger:3.3},{t:11,v:2.7,trigger:3.3},{t:12,v:3.3,trigger:3.3}];assert.equal(C.analyze(s,{...cfg,trigger_window_s:20}).events[0].trigger_lag_s,null);});
test('boundary onset is not assigned a false trigger lag',()=>{const s=[{t:0,v:2.8,trigger:0},{t:1,v:2.7,trigger:3.3},{t:2,v:3.3,trigger:3.3}];assert.equal(C.analyze(s,{...cfg,trigger_window_s:20}).events[0].trigger_lag_s,null);});
test('invalid threshold ordering is rejected',()=>{assert.throws(()=>C.analyze(rows([3.3,3.2]),{...cfg,recover_v:2.9}),/Thresholds/);assert.throws(()=>C.analyze(rows([3.3,3.2]),{...cfg,nominal_v:NaN}),/finite/);});
test('duplicates and reversed time are rejected, not sorted',()=>{for(const t of [0,-1])assert.throws(()=>C.analyze([{t:0,v:3},{t,v:3}],cfg),/strictly increasing/);});
test('nonfinite and inconsistent trigger samples are rejected',()=>{assert.throws(()=>C.analyze([{t:0,v:NaN},{t:1,v:3}],cfg),/finite/);assert.throws(()=>C.analyze([{t:0,v:3,trigger:0},{t:1,v:3}],cfg),/missing/);});
test('quoted CSV and BOM parse via upstream parser',()=>{const t=C.parseTable('\ufeff"t","v"\r\n"0","3.3"\r\n"1","2.8"\r\n');assert.deepEqual(t.headers,['t','v']);close(C.toSamples(t,map)[1].v,2.8);});
test('semicolon CSV, decimal comma, ms and mV normalization',()=>{const t=C.parseTable('t;v\n0,0;3300,0\n1,0;2800,0');const s=C.toSamples(t,{...map,decimal:',',time_unit:'ms',voltage_unit:'mV'});close(s[1].t,.001);close(s[1].v,2.8);});
test('metadata is skipped only on explicit request',()=>{const text='Model X\nCapture exported\nt,v\n0,3.3\n1,2.8';assert.throws(()=>C.parseTable(text));assert.equal(C.parseTable(text,{skip_lines:2}).records.length,2);});
test('missing units are rejected rather than guessed',()=>{assert.throws(()=>C.toSamples(C.parseTable('t,v\n0,3\n1,3'),{...map,time_unit:''}),/Confirm/);});
test('missing cells, hex, infinity and overflows are rejected',()=>{for(const cell of ['', '0x10','Infinity','1e999','NA'])assert.throws(()=>C.toSamples(C.parseTable(`t,v\n0,3.3\n1,${cell}`),map));});
test('malformed rows and duplicate headers are rejected',()=>{assert.throws(()=>C.parseTable('t,v\n0,3\n1,3,4'), /delimiter|column count/);assert.throws(()=>C.parseTable('t,t\n0,3\n1,3'),/unique/);});
test('unterminated quotes are not accepted',()=>{assert.throws(()=>C.parseTable('t,v\n0,3\n1,"3'),/parse error|delimiter/);});
test('same time and signal column is rejected',()=>{assert.throws(()=>C.toSamples(C.parseTable('t,v\n0,3\n1,3'),{...map,voltage_column:'t'}),/different/);});
test('input limits and non-integer skip count enforced',()=>{assert.throws(()=>C.parseTable('x'.repeat(C.MAX_BYTES+1)),/limit/);assert.throws(()=>C.parseTable('t,v\n0,3\n1,3',{skip_lines:1.5}),/integer/);});
test('large capture checks dt beyond the first thousand rows',()=>{const s=Array.from({length:150000},(_,i)=>({t:i+(i>=140000?10:0),v:3.3}));const r=C.analyze(s,cfg);assert.equal(r.capture.max_sample_interval_s,11);assert.equal(r.gaps.length,1);});
test('synthetic demo is deterministic and has 2 retained events plus one filtered short dip',()=>{assert.equal(C.demoCsv(),C.demoCsv());const t=C.parseTable(C.demoCsv());const s=C.toSamples(t,{...map,time_column:'time_s',voltage_column:'rail_v',trigger_column:'trigger_v',trigger_unit:'V'});const r=C.analyze(s,{...cfg,recover_v:3.08,min_duration_s:20e-6});assert.equal(r.capture.sample_count,4001);assert.equal(r.event_counts.kept,2);assert.equal(r.event_counts.raw,3);assert.equal(r.triggers.length,2);assert.equal(r.event_counts.incomplete,0);});
test('HTML report escapes untrusted source names and notes',()=>{const s=rows([3.3,2.8,3.3]);const r=C.analyze(s,cfg);r.source={name:'<img src=x onerror=alert(1)>',origin:'USER CSV',note:'</pre><script>alert(1)</script>'};const html=R.html(s,r);assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<img src=x'));assert.ok(html.includes("default-src 'none'"));});
test('vendored Papa Parse exactly matches verified upstream Git blob',()=>{const b=fs.readFileSync(require.resolve('../vendor/papaparse.min.js'));const h=crypto.createHash('sha1').update(Buffer.from('blob '+b.length+'\0')).update(b).digest('hex');assert.equal(h,'f31411042b80599f9dd6126ff8fd41f8fa8f68fb');});
test('translation invariance under time-origin offset',()=>{const a=rows([3.3,3.3,2.7,3.3]),r=C.analyze(a,cfg),q=C.analyze(a.map(s=>({...s,t:s.t+100})),cfg);close(q.events[0].duration_s,r.events[0].duration_s);close(q.events[0].start_s,r.events[0].start_s+100);});
